---
title: Microshare
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
permalink: pretty
gems:
- jekyll-redirect-from
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
baseurl: ''
url: ''
description: Store, Protect & Share the data you want, the way you want.
email: docs@microshare.io
twitter: microshare_io
github: microshare
social_logo_path: "/assets/brand/default-icon.png"
social_image_path: "/assets/brand/default-icon.png"
current_version: 2
docs_version: 2
repo: https://github.com/microshare/microshare.github.io
blog: https://microshare.io/blog
